### ISSUE TITLE
Format of recipes.txt?

### ISSUE THREAD

**Issue by peterfarge** [gemforce-team/wGemCombiner#38]
I want to save my own recipes in the txt file, like it is mentioned in the help and in the example recipes.txt.  But the recipes do not appear in the drop down list. I have seen the recipes.txt has a unix format. I have uncommented some recipes there, but it does not work. Maybe the format has changed? I would be nice if the comment line above the recipe would appear as the recipe name within the GUI.

**Comment by 12345ieee** [comment]
Uhm, the newlines shouldn't matter.
The example file has unix newlines because I develop on Linux, but it should work with either.

Be sure you are creating it in the same folder as the exe, and that you have permissions to read it.
Failing that, attach it to this issue and I'll try to take a look.

I'm sorry but importing comments as names would require substantial work, you are welcome to send a patch, but I won't code it myself.

**Comment by peterfarge** [comment]
The folder is readable . If you take your recipes.txt from the precompiled download and uncomment a recipe, then it appears in the drop down list? Under what name?

**Comment by 12345ieee** [comment]
Ah, there is a bit of confusion here.

Custom recipes are treated the same as normal recipes, so if you add, let's say, `(o+o)`, you'll find it together with the other orange combines, so under `Orange combine` (or `Leech combine` if you changed the option) you'll find a recipe of length 2 and growth 0.46.

If you add a recipe that is already pre-included, you won't see any change, as the engine discards duplicated recipes.

**Comment by peterfarge** [comment]
Ah, thats the problem. I always looked in the spec/combine dropdown box for a "custom" entry (or similar name) when I edited the recipe.txt. It works now. Thanks :)
